# AndroidX enable
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Kotlin DSL
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.nonTransitiveRClass=true

# Workaround for AGP 8 ConstraintHandler bug with Kotlin alignment
android.disableKotlinStdlibAlignment=true

